### ISSUE TITLE
Code for bayes looks wrong

### ISSUE THREAD

**Issue by victorconan** [dimonenka/DEDPUL#2]
This piece of code for bayes option looks wrong
https://github.com/dimonenka/DEDPUL/blob/ae710fe2017201ceb9a205fc3cbbf73fc8f7a60c/algorithms.py#L516

**Comment by dimonenka** [comment]
Hi!
Could you please elaborate?
The function estimate_preds_cv does return 3 tensors if bayes==True.
That said, there might be bugs in the Bayesian implementation. It was not tested as properly since it isn't included in the paper.
